name: Build Project
on: push
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install
            - name: Build application
              run: yarn build
            - name: Upload Builded project
              uses: actions/upload-artifact@v3
              with: 
                path: build
                name: builded-project
    dowload:
        needs: build
        runs-on: ubuntu-latest
        steps: 
            - name: Download builded project
              uses: actions/download-artifact@v3
              with: 
                name: builded-project